baseURL = "https://ikhsan.dev/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Abdul Fattah Ikhsan | Fullstack Developer"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]
[Author]
    name = "Abdul Fattah Ikhsan"
[params]
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/ikhsanalatsary"
    [[params.links]]
        icon = "facebook"
        title = "Facebook"
        url = "https://www.facebook.com/ikhsan.alatsary"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/@abdfattahikhsan"
    [[params.links]]
        icon = "telegram"
        title = "Telegram"
        url = "https://t.me/ikhsaan"
    [[params.links]]
        icon = "medium"
        title = "Medium"
        url = "https://medium.com/@abdfattahikhsan"
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/abdul-fattah-ikhsan"
